title: YTS
author: YTS
description: Un lugar para mostrar la música y más
baseurl: "" # Deja esto vacío si es tu sitio principal
url: "https://ytsmusica.com"
feed:
  path: "feed.xml" # Esto es opcional; jekyll-feed usa este nombre por defecto
  
# Configuración de construcción
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  parse_block_html: true
  parse_span_html: true
  html_to_native: false

permalink: /:categories/:title/

# Sass stuff
sass:
  sass_dir: _sass
  style: compressed

# Excluir archivos y carpetas
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Colecciones
collections:
  releases:
    output: true
    permalink: /releases/:title/
  posts:
    output: true
    permalink: /posts/:title/

# Valores predeterminados para el front matter
defaults:
  - scope:
      path: ""
      type: "releases"
    values:
      layout: "release"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# no github default theme
theme: null